---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ddclient"
      include_role:
        name: "ddclient"
      vars:
        ddclient_executable_path: /usr/local/bin/ddclient-test
        ddclient_configfile: /etc/ddclient-test.conf
        ddclient_pidfile: /var/run/ddclient-test.pid
        ddclient_systemd_unit: ddclient-test
